// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2018.commands;
import org.usfirst.frc4089.Stealth2018.utilities.LogMech;
import org.usfirst.frc4089.Stealth2018.Robot;
import org.usfirst.frc4089.Stealth2018.subsystems.*;

import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class SpeedShiftUp extends Command {

	public SpeedShiftUp() {
        requires(Robot.drive);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	if (Robot.drive.mSpeedPreset == Drive.SpeedPreset.Slow) {
    		Robot.drive.SetSpeedPreset(Drive.SpeedPreset.Medium);
    	} else if (Robot.drive.mSpeedPreset == Drive.SpeedPreset.Medium) {
    		Robot.drive.SetSpeedPreset(Drive.SpeedPreset.Fast);
    	} else if (Robot.drive.mSpeedPreset == Drive.SpeedPreset.Fast) {
    		Robot.drive.SetSpeedPreset(Drive.SpeedPreset.FullSpeed);
    	} else if (Robot.drive.mSpeedPreset == Drive.SpeedPreset.FullSpeed) {
    		//do nothing it is at max speed
    	}
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
