// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4089.Stealth2018.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc4089.Stealth2018.Robot;
import org.usfirst.frc4089.Stealth2018.utilities.*;

/**
 *
 */
public class WaitTime extends Command {

  

  StopWatch mWaitTime = new StopWatch(1000);

  
  public WaitTime() {

    
    mWaitTime.setTime(1000);
  }
  
  private int SetTime;

  public WaitTime(int setTime) {
    mWaitTime.setTime(setTime);
    SetTime = setTime;
  }

  // Called just before this Command runs the first time
  @Override
  protected void initialize() {
	  Robot.logging.LogEvent("WaitTime("+SetTime+" Source: Commands.DrivePathAction");
    mWaitTime.reset();
  }

  // Called repeatedly when this Command is scheduled to run
  @Override
  protected void execute() {
  }

  // Make this return true when this Command no longer needs to run execute()
  @Override
  protected boolean isFinished() {
    return mWaitTime.isExpired();
  }

  // Called once after isFinished returns true
  @Override
  protected void end() {
  }

  // Called when another command which requires one or more of the same
  // subsystems is scheduled to run
  @Override
  protected void interrupted() {
	  end();
  }
}
